name: network_queue_manager
description: "Gerencie requisições offline no Flutter com fila automática e armazenamento no Hive."
version: 0.0.1
repository: https://github.com/MarciohsjOliveira/network_queue_manager
issue_tracker: https://github.com/MarciohsjOliveira/network_queue_manager/issues
homepage: https://github.com/MarciohsjOliveira/network_queue_manager
environment:
  sdk: ">=3.7.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
dev_dependencies:
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0
  test: ^1.21.0